#!/usr/bin/env bash
shopt -s extglob

# WARNING
#
# this is messy and fragile


# for file in 13.tex 14.tex 18.tex #  selection for testing
for file in $(ls +([0-9]).tex | sort -n)
do
cat "$file" | awk '
BEGIN   {
  going=1;reading=0
}
/^\\def\\no{[^}]*/  {
  n=substr($0, 9, length($0)-9)
}
going && /^\\def\\theintegral{.*\\)}/  {
  i=substr($0, 20, length($0)-22);
  going=0
}
reading && /^.*\\)}$/  {
  i = i " " substr($0,0,length($0)-3);
  reading=0
}
reading  {
  i = i " " $0
}
going && /^\\def\\theintegral{.*$/  {
  i=substr($0, 20, length($0)-19);reading=1
}
END  {
  gsub(/^ *\\int/,"",i)
  gsub(/%/," ",i)      # will not remove any actual comments!
  gsub(/=.*$/,"",i)
  match(i,/^.*\\dif/);i=substr(i,0,RLENGTH-4)
  gsub(/\\[ ,;]$/,"",i)
  print "\\listintegral{" n "}{" i "}"
}
'
done
